[Database]
host = "localhost"
port = "3306"
username = "root"
password = ""
dbname = "test"

[[Files]]
csvfile = "file1.csv"
delimiter = ","
hasheader = true
table = "table1"
[Files.colmap]
"1" = "column1"
"2" = "column2"
"3" = "column3"
"4" = "column4"
"5" = "column5"

[[Files]]
csvfile = "file2.csv"
delimiter = ";"
hasheader = true
table = "table2"
[Files.colmap]
"5" = "column1"
"4" = "column2"
"3" = "column3"
"2" = "column4"
"1" = "column5"

[[Files]]
csvfile = "file3.csv"
delimiter = "\t"
hasheader = true
table = "table3"
colmap = { "101" = "col1", "102" = "col2", "103" = "col3" }
