[Database]
host = "localhost"
port = "3306"
username = "root"
password = ""
dbname = "test"

[[Files]]
csvfile = "file1.csv"
delimiter = ","
hasheader = true
table = "table1"
truncate = true
[Files.colmap]
"column1" = "1"
"column2" = "2"
"column3" = "3"
"column4" = "4"
"column5" = "5"

[[Files]]
csvfile = "file2.csv"
delimiter = ";"
hasheader = true
table = "table2"
[Files.colmap]
"column1" = "5"
"column2" = "4"
"column3" = "3"
"column4" = "2"
"column5" = "1"
"column6" = "1"

[[Files]]
csvfile = "file3.csv"
delimiter = "\t"
hasheader = true
table = "table3"
colmap = { "col1" = "101", "col2" = "102", "col3" = "103" }
