CREATE TABLE `table1` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`Column1` VARCHAR(50) NULL DEFAULT NULL,
	`Column2` VARCHAR(50) NULL DEFAULT NULL,
	`Column3` VARCHAR(50) NULL DEFAULT NULL,
	`Column4` VARCHAR(50) NULL DEFAULT NULL,
	`Column5` VARCHAR(50) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
) COLLATE='latin1_swedish_ci' ENGINE=InnoDB;

CREATE TABLE `table2` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`Column1` VARCHAR(50) NULL DEFAULT NULL,
	`Column2` VARCHAR(50) NULL DEFAULT NULL,
	`Column3` VARCHAR(50) NULL DEFAULT NULL,
	`Column4` VARCHAR(50) NULL DEFAULT NULL,
	`Column5` VARCHAR(50) NULL DEFAULT NULL,
	`Column6` VARCHAR(50) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
) COLLATE='latin1_swedish_ci' ENGINE=InnoDB;
